- Updated syntax/variable names

diff --git a/aur_manager b/aur_manager
--- a/aur_manager
+++ b/aur_manager
@@ -5,42 +5,41 @@ Author: Ryan Cool
 Date: 2024-02-13
 
 Simple script to check AUR repos for updates. This assumes that
-each directory set in aur_dir is a repo, so if aur_dir is empty
+each directory set in AUR_DIR is a repo, so if AUR_DIR is empty
 or doesnt have any directories in it, it will not run.
 '
 
 # Set AUR DIR
-aur_dir="/home/$USER/.local/aur"
-
+AUR_DIR="${HOME}/.local/aur"
 
 #########################################
 #       DONT CHANGE BELOW               #
 #########################################
 
-CONFIG_FILE="$aur_dir/aur-config.json"
+CONFIG_FILE="${AUR_DIR}/aur-config.json"
 
 # Check if jq is installed
-if ! command -v jq &> /dev/null; then
+if ! command -v jq &>/dev/null; then
     printf "jq is required but not installed. Please install it and try again.\n"
-    exit 1  # indicates code failure
+    exit 1 # indicates code failure
 fi
 
 check_config_file() {
-    if [[ ! -f "$CONFIG_FILE" ]]; then
-        printf "\nConfiguration file '%s' does not exist.\n" "$CONFIG_FILE"
+    if [[ ! -f "${CONFIG_FILE}" ]]; then
+        printf "\nConfiguration file '%s' does not exist.\n" "${CONFIG_FILE}"
         read -p "Would you like to create it? (y/n) " -n 1 -r
         if [[ $REPLY =~ ^[Yy]$ ]]; then
             # Use printf to initiate creation of default config file
             printf '{
   "repos": []
-}' > "$CONFIG_FILE"
-            # Loop through repos in aur_dir
-            for repo in "$aur_dir"/*/; do
-                repo_name=$(basename "$repo")
+}' >"${CONFIG_FILE}"
+            # Loop through repos in AUR_DIR
+            for repo in "${AUR_DIR}"/*/; do
+                repo_name=$(basename "${repo}")
                 # Add each repo to specified config file using jq
-                jq --arg name "$repo_name" '.repos += [{"name": $name, "install": ""}]' "$CONFIG_FILE" > tmp.$$.json && mv tmp.$$.json "$CONFIG_FILE"
+                jq --arg name "${repo_name}" '.repos += [{"name": $name, "install": ""}]' "${CONFIG_FILE}" >tmp.$$.json && mv tmp.$$.json "${CONFIG_FILE}"
             done
-            printf "\nConfiguration file '%s' has been created.\n" "$CONFIG_FILE"
+            printf "\nConfiguration file '%s' has been created.\n" "${CONFIG_FILE}"
         else
             printf "\nExiting the script. Please create the configuration file manually.\n"
             printf "\n The file should have this structure:\n"
@@ -52,7 +51,7 @@ check_config_file() {
         }
     ]
 }\n'
-            exit 1  # Exit if the user does not want to create the file
+            exit 1 # Exit if the user does not want to create the file
         fi
     fi
 }
@@ -63,31 +62,31 @@ check_config_file
 #   Functions used in Main    #
 ###############################
 
-# Reads all git aur repos in $aur_dir to an array
+# Reads all git aur repos in $AUR_DIR to an array
 gather_repos() {
-    printf "\nGathering AUR repos in %s\n" "$aur_dir"
-    cd "$aur_dir" || exit 1
+    printf "\nGathering AUR repos in %s\n" "${AUR_DIR}"
+    cd "${AUR_DIR}" || exit 1
     readarray -t repos < <(find . -mindepth 1 -maxdepth 1 -type d -printf '%P\n')
 }
 
 # Checks to see if package is currently installed
 check_sys_installed() {
     package="$1"
-    cs_install_status=$(jq -r --arg repo "$package" '.repos[] | select(.name == $repo) | .install' "$CONFIG_FILE")
-    if pacman -Qs "$package" > /dev/null; then
+    cs_install_status=$(jq -r --arg repo "${package}" '.repos[] | select(.name == $repo) | .install' "${CONFIG_FILE}")
+    if pacman -Qs "${package}" >/dev/null; then
         return 0
     else
-        printf "\n%s is not installed\n" "$package"
+        printf "\n%s is not installed\n" "${package}"
         read -p "Would you like to install it? (y/n) " -n 1 -r
         if [[ $REPLY =~ ^[Yy]$ ]]; then
-            printf "\n%s will be installed" "$package"
-            update_repo_install_status "$package" "yes"
+            printf "\n%s will be installed" "${package}"
+            update_repo_install_status "${package}" "yes"
         else
-            printf "\nSkipping installation for %s\n" "$package"
-            if [[ "$cs_install_status" == "no" ]]; then
-            printf "\nInstallation status for %s is already 'no'. Continuing...\n" "$package"
+            printf "\nSkipping installation for %s\n" "${package}"
+            if [[ "${cs_install_status}" == "no" ]]; then
+                printf "\nInstallation status for %s is already 'no'. Continuing...\n" "${package}"
             else
-                update_repo_install_status "$package" "no"
+                update_repo_install_status "${package}" "no"
             fi
         fi
     fi
@@ -99,15 +98,15 @@ update_repo_install_status() {
     local new_status="$2"
 
     # Attempt to update the install status in the config file using jq
-    if jq --arg repo "$repo_name" --arg status "$new_status" '(.repos[] | select(.name == $repo).install) = $status' "$CONFIG_FILE" > tmp.$$.json; then
+    if jq --arg repo "${repo_name}" --arg status "${new_status}" '(.repos[] | select(.name == $repo).install) = $status' "${CONFIG_FILE}" >tmp.$$.json; then
         # mv tmp file to the orig config file
-        mv tmp.$$.json "$CONFIG_FILE"
-        printf "\nUpdated %s status to '%s' in the config file.\n" "$repo_name" "$new_status"
+        mv tmp.$$.json "${CONFIG_FILE}"
+        printf "\nUpdated %s status to '%s' in the config file.\n" "${repo_name}" "${new_status}"
     else
         # If jq fails, handle the error
-        printf "\nFailed to update %s status in the config file.\n" "$repo_name"
-        rm tmp.$$.json  # Clean up the temporary file if it exists
-        return 1  # indicates code failure
+        printf "\nFailed to update %s status in the config file.\n" "${repo_name}"
+        rm tmp.$$.json # Clean up the temporary file if it exists
+        return 1       # indicates code failure
     fi
 }
 
@@ -116,13 +115,13 @@ check_repo_install_status() {
     local repo_name="$1"
 
     # Uses jq to parse JSON and find the install status of current repo being passed
-    cr_install_status=$(jq -r --arg repo "$repo_name" '.repos[] | select(.name == $repo) | .install' "$CONFIG_FILE")
+    cr_install_status=$(jq -r --arg repo "${repo_name}" '.repos[] | select(.name == $repo) | .install' "${CONFIG_FILE}")
 
     # Checks if install status is empty
-    if [[ -z "$cr_install_status" ]]; then
-        printf "%s status not found in the config file." "$repo_name"
+    if [[ -z "${cr_install_status}" ]]; then
+        printf "%s status not found in the config file." "${repo_name}"
     else
-        printf "%s" "$cr_install_status"
+        printf "%s" "${cr_install_status}"
     fi
 }
 
@@ -130,11 +129,11 @@ check_repo_install_status() {
 update_repo() {
     repo_to_check="$1"
     # If install status is no, this will continue to the next repo
-    if [[ $(check_repo_install_status "$repo_to_check") == "no" ]]; then
-        printf "Skipping %s, install status already set to no" "$repo_to_check"
+    if [[ $(check_repo_install_status "${repo_to_check}") == "no" ]]; then
+        printf "Skipping %s, install status already set to no" "${repo_to_check}"
         return 0
     fi
-    cd "$repo_to_check" || exit 1
+    cd "${repo_to_check}" || exit 1
     branch=$(git rev-parse --abbrev-ref HEAD)
     # Checks if local repo is out of date with remote repo
     if git remote show origin | grep -q "local out of date"; then
@@ -143,55 +142,55 @@ update_repo() {
             git diff origin/"${branch}" "${branch}"
             read -p "Continue (c) or Skip (s) to next repo?" -r choice
             case "${choice}" in
-                [Cc]* )
-                    git remote update origin
-                    # Prompts user to set install status if it's currently empty
-                    if [[ -z $(check_repo_install_status "$repo_to_check") ]]; then
-                        printf "\nInstall status for %s is empty\n" "$repo_to_check"
-                        read -p "Would you like to install it? (y/n) " -n 1 -r
-                        if [[ $REPLY =~ ^[Yy]$ ]]; then
-                            update_repo_install_status "$repo_to_check" "yes"
-                            git pull origin "$branch"
-                            makepkg -sirc
-                            git clean -dfx
-                        else
-                            update_repo_install_status "$repo_to_check" "no"
-                        fi
-                    # If install status is yes, this pulls from git origin main branch
-                    # and tries to run makepkg for installation
-                    elif [[ $(check_repo_install_status "$repo_to_check") == "yes" ]]; then
-                        git pull origin "$branch"
+            [Cc]*)
+                git remote update origin
+                # Prompts user to set install status if it's currently empty
+                if [[ -z $(check_repo_install_status "${repo_to_check}") ]]; then
+                    printf "\nInstall status for %s is empty\n" "${repo_to_check}"
+                    read -p "Would you like to install it? (y/n) " -n 1 -r
+                    if [[ $REPLY =~ ^[Yy]$ ]]; then
+                        update_repo_install_status "${repo_to_check}" "yes"
+                        git pull origin "${branch}"
                         makepkg -sirc
                         git clean -dfx
                     else
-                    # Extremely generic and vague error message....Need to add better error handling in the future
-                        printf "\nError occurred\n"
+                        update_repo_install_status "${repo_to_check}" "no"
                     fi
-                    break
-                    ;;
-                [Ss]* )
-                    return 0
-                    ;;
-                * )
-                    echo "Please answer 'c' to continue or 's' to skip"
-                    ;;
-                esac
-            done
+                # If install status is yes, this pulls from git origin main branch
+                # and tries to run makepkg for installation
+                elif [[ $(check_repo_install_status "${repo_to_check}") == "yes" ]]; then
+                    git pull origin "${branch}"
+                    makepkg -sirc
+                    git clean -dfx
+                else
+                    # Extremely generic and vague error message....Need to add better error handling in the future
+                    printf "\nError occurred\n"
+                fi
+                break
+                ;;
+            [Ss]*)
+                return 0
+                ;;
+            *)
+                echo "Please answer 'c' to continue or 's' to skip"
+                ;;
+            esac
+        done
     else
         printf "\n%s is up to date, checking next repo\n" "$1"
     fi
-    cd "$aur_dir" || exit 1
+    cd "${AUR_DIR}" || exit 1
 }
 
 main() {
     gather_repos
     if [[ ${#repos[@]} -ge 1 ]]; then
         for repo in "${repos[@]}"; do
-            check_sys_installed "$repo"
-            update_repo "$repo"
+            check_sys_installed "${repo}"
+            update_repo "${repo}"
         done
     else
-        printf "\nNo repos found in %s\n" "$aur_dir"
+        printf "\nNo repos found in %s\n" "${AUR_DIR}"
     fi
 }
 
